# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/teriyaki/Música/Transformer_FASHION_MNIST/TRANFOVERSINOPENCV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/teriyaki/Música/Transformer_FASHION_MNIST/TRANFOVERSINOPENCV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teriyaki/Música/Transformer_FASHION_MNIST/TRANFOVERSINOPENCV/CMakeFiles /home/teriyaki/Música/Transformer_FASHION_MNIST/TRANFOVERSINOPENCV//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teriyaki/Música/Transformer_FASHION_MNIST/TRANFOVERSINOPENCV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FashionMNISTTransformer

# Build rule for target.
FashionMNISTTransformer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FashionMNISTTransformer
.PHONY : FashionMNISTTransformer

# fast build rule for target.
FashionMNISTTransformer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/build
.PHONY : FashionMNISTTransformer/fast

include/cuda_ops.o: include/cuda_ops.cu.o
.PHONY : include/cuda_ops.o

# target to build an object file
include/cuda_ops.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/include/cuda_ops.cu.o
.PHONY : include/cuda_ops.cu.o

include/cuda_ops.i: include/cuda_ops.cu.i
.PHONY : include/cuda_ops.i

# target to preprocess a source file
include/cuda_ops.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/include/cuda_ops.cu.i
.PHONY : include/cuda_ops.cu.i

include/cuda_ops.s: include/cuda_ops.cu.s
.PHONY : include/cuda_ops.s

# target to generate assembly for a file
include/cuda_ops.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/include/cuda_ops.cu.s
.PHONY : include/cuda_ops.cu.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/main.cpp.s
.PHONY : main.cpp.s

src/matrix.o: src/matrix.cpp.o
.PHONY : src/matrix.o

# target to build an object file
src/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/matrix.cpp.o
.PHONY : src/matrix.cpp.o

src/matrix.i: src/matrix.cpp.i
.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/matrix.cpp.i
.PHONY : src/matrix.cpp.i

src/matrix.s: src/matrix.cpp.s
.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/matrix.cpp.s
.PHONY : src/matrix.cpp.s

src/matrix_cuda.o: src/matrix_cuda.cu.o
.PHONY : src/matrix_cuda.o

# target to build an object file
src/matrix_cuda.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/matrix_cuda.cu.o
.PHONY : src/matrix_cuda.cu.o

src/matrix_cuda.i: src/matrix_cuda.cu.i
.PHONY : src/matrix_cuda.i

# target to preprocess a source file
src/matrix_cuda.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/matrix_cuda.cu.i
.PHONY : src/matrix_cuda.cu.i

src/matrix_cuda.s: src/matrix_cuda.cu.s
.PHONY : src/matrix_cuda.s

# target to generate assembly for a file
src/matrix_cuda.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/matrix_cuda.cu.s
.PHONY : src/matrix_cuda.cu.s

src/mnist_loader.o: src/mnist_loader.cpp.o
.PHONY : src/mnist_loader.o

# target to build an object file
src/mnist_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/mnist_loader.cpp.o
.PHONY : src/mnist_loader.cpp.o

src/mnist_loader.i: src/mnist_loader.cpp.i
.PHONY : src/mnist_loader.i

# target to preprocess a source file
src/mnist_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/mnist_loader.cpp.i
.PHONY : src/mnist_loader.cpp.i

src/mnist_loader.s: src/mnist_loader.cpp.s
.PHONY : src/mnist_loader.s

# target to generate assembly for a file
src/mnist_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/mnist_loader.cpp.s
.PHONY : src/mnist_loader.cpp.s

src/transformer.o: src/transformer.cpp.o
.PHONY : src/transformer.o

# target to build an object file
src/transformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/transformer.cpp.o
.PHONY : src/transformer.cpp.o

src/transformer.i: src/transformer.cpp.i
.PHONY : src/transformer.i

# target to preprocess a source file
src/transformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/transformer.cpp.i
.PHONY : src/transformer.cpp.i

src/transformer.s: src/transformer.cpp.s
.PHONY : src/transformer.s

# target to generate assembly for a file
src/transformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FashionMNISTTransformer.dir/build.make CMakeFiles/FashionMNISTTransformer.dir/src/transformer.cpp.s
.PHONY : src/transformer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FashionMNISTTransformer"
	@echo "... include/cuda_ops.o"
	@echo "... include/cuda_ops.i"
	@echo "... include/cuda_ops.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/matrix_cuda.o"
	@echo "... src/matrix_cuda.i"
	@echo "... src/matrix_cuda.s"
	@echo "... src/mnist_loader.o"
	@echo "... src/mnist_loader.i"
	@echo "... src/mnist_loader.s"
	@echo "... src/transformer.o"
	@echo "... src/transformer.i"
	@echo "... src/transformer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

